const apiRoutes = {
  baseUrl: import.meta.env.VITE_API_BASE_URL,
  Admin: "api/",
  Auth: "auth/",
  AdminProfile: "admin/profile/",
  MemberRegister: "register/",
  Members: "members/members/",
  MemberDetail: (id) => `members/members/${id}/`,
  Login: "login/",
  Plans: "plans/membership-plans/",
  PlansDetails: (id) => `plans/membership-plans/${id}/`,
  Trainers: "trainers/byadmintrainers/",
  TrainerDetail: (id) => `trainers/trainers/${id}/`,
  WorkoutPlans: "trainers/workout-plans/",
  Payments: "payments/payments/create/",
  Notifications: "notifications/",
  NotificationRead: (id) => `notifications/${id}/read/`,
  NotificationMarkAllRead: "notifications/mark-all-read/",
  NotificationDelete: (id) => `notifications/${id}/read/`,
  NotificationUnreadCount: "notifications/unread-count/",
  PaymentsList: "payments/payments/list/",
  RevenueStats: "payments/revenue/stats/",
  MemberWorkoutPlans: "members/my-workout-plans/",
  MemberAttendance: "attendance/members/",
  TrainerAttendance: "attendance/trainers/",
  TrainerMemberAttendance: "attendance/trainer/members/",
  AdminAttendanceOverview: "attendance/admin/overview/",
  TrainerDietPlans: "diets/trainer-plans/",
  TrainerDietPlanDetail: (id) => `diets/trainer-plans/${id}/`,
  MemberDietPlans: "diets/my-plans/",
  DailyProgress: "diets/daily-progress/",
  MemberProfile: "members/profile/",
  MemberProgress: "members/my-progress/",
  TrainerMemberProgress: (memberId) => `members/members/${memberId}/progress/`,
  ChangePassword: "change-password/",
  PasswordReset: "password-reset/",
  PasswordResetConfirm: "password-reset-confirm/",
};

export default apiRoutes;
